In [64]:
data={
    'Name':['Anuj','Ranjan','Amit','Priya','Ravi','Vaibhav','Suman'],
    'Marks':[50,70,44,33,22,11,77],
    'Gender':['Male','Male','Male','Female','Male','Male','Female']

}

In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.DataFrame(data)

In [44]:
df

      Name  Marks  Gender
0     Anuj     50    Male
1   Ranjan     70    Male
2     Amit     44    Male
3    Priya     33  Female
4     Ravi     22    Male
5  Vaibhav     11    Male
6    Suman     77  Female

In [45]:
df.head(3)

     Name  Marks Gender
0    Anuj     50   Male
1  Ranjan     70   Male
2    Amit     44   Male

In [46]:
df.tail(3)

      Name  Marks  Gender
4     Ravi     22    Male
5  Vaibhav     11    Male
6    Suman     77  Female

In [47]:
df.shape

(7, 3)

In [48]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 7
Columns: 3

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 367.0 bytes

In [50]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

In [51]:
df.isnull()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [52]:
df.describe()

           Marks
count   7.000000
mean   43.857143
std    24.134544
min    11.000000
25%    27.500000
50%    44.000000
75%    60.000000
max    77.000000

In [53]:
df["Gender"].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

In [54]:
df["Gender"].value_counts()

Gender
Male      5
Female    2
Name: count, dtype: int64

In [55]:
df["Marks"].sort_values()

5    11
4    22
3    33
2    44
0    50
1    70
6    77
Name: Marks, dtype: int64

In [56]:
df["Marks"].sort_values(ascending=False)

6    77
1    70
0    50
2    44
3    33
4    22
5    11
Name: Marks, dtype: int64

In [57]:
df[(df["Marks"] >= 90) & (df["Marks"] <= 100)].shape[0]

0

In [58]:
df["Marks"].between(90, 100, inclusive="both").sum()

np.int64(0)

In [59]:
df["Marks"].mean()

np.float64(43.857142857142854)

In [60]:
df["Half Marks"] = df["Marks"] / 2

In [61]:
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})

In [62]:
df

      Name  Marks  Gender  Half Marks
0     Anuj     50       0        25.0
1   Ranjan     70       0        35.0
2     Amit     44       0        22.0
3    Priya     33       1        16.5
4     Ravi     22       0        11.0
5  Vaibhav     11       0         5.5
6    Suman     77       1        38.5